# Generated by Django 6.0.4 on 2026-04-15 16:23

import django.core.validators
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_active_drafts(apps, schema_editor):
    AssessmentEvaluation = apps.get_model('assessments', 'AssessmentEvaluation')

    duplicated_professionals = (
        AssessmentEvaluation.objects.filter(is_active=True, status='rascunho')
        .values('professional_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )

    for row in duplicated_professionals:
        professional_id = row['professional_id']
        drafts = AssessmentEvaluation.objects.filter(
            professional_id=professional_id,
            is_active=True,
            status='rascunho',
        ).order_by('-modified', '-created', '-id')

        keep = drafts.first()
        if keep:
            drafts.exclude(id=keep.id).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_secure_child_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assessmentevaluation',
            name='child_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)], verbose_name='Child age'),
        ),
        migrations.RunPython(dedupe_active_drafts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='assessmentevaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'rascunho')), fields=('professional',), name='uq_active_draft_per_professional'),
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('name', 'state_code'), name='uq_municipality_name_state_code'),
        ),
    ]
