# Generated by Django 6.0.4 on 2026-05-02 18:55

import apps.core.validators
import apps.users.managers
import apps.users.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_jsonform.models.fields
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SPECIALIST', 'Specialist'), ('PARENT', 'Parent')], max_length=20, verbose_name='Role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ['first_name', 'last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', apps.users.managers.AdminManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['first_name', 'last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', apps.users.managers.ParentManager()),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
            ],
            options={
                'verbose_name': 'Specialist',
                'verbose_name_plural': 'Specialists',
                'ordering': ['first_name', 'last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', apps.users.managers.SpecialistManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, help_text='Maximum size: 5MB. Allowed formats: .jpg, .jpeg, .png', upload_to=apps.users.utils.get_user_upload_path, validators=[apps.core.validators.FileSizeValidator(max_size=5, unit='MB'), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Avatar')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese')], default='pt-br', max_length=10, verbose_name='Language')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=100, verbose_name='Timezone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='users.admin', verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Admin profile',
                'verbose_name_plural': 'Admin profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, help_text='Maximum size: 5MB. Allowed formats: .jpg, .jpeg, .png', upload_to=apps.users.utils.get_user_upload_path, validators=[apps.core.validators.FileSizeValidator(max_size=5, unit='MB'), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Avatar')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese')], default='pt-br', max_length=10, verbose_name='Language')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=100, verbose_name='Timezone')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('address', django_jsonform.models.fields.JSONField(blank=True, default=dict, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='users.parent', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Parent profile',
                'verbose_name_plural': 'Parent profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, help_text='Maximum size: 5MB. Allowed formats: .jpg, .jpeg, .png', upload_to=apps.users.utils.get_user_upload_path, validators=[apps.core.validators.FileSizeValidator(max_size=5, unit='MB'), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Avatar')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese')], default='pt-br', max_length=10, verbose_name='Language')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=100, verbose_name='Timezone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to='users.specialist', verbose_name='Specialist')),
            ],
            options={
                'verbose_name': 'Specialist profile',
                'verbose_name_plural': 'Specialist profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
