# Generated by Django 6.0.5 on 2026-05-06 22:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_preferences_and_password_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Português')], default='pt-br', max_length=10, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Português')], default='pt-br', max_length=10, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Número de telefone'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Português')], default='pt-br', max_length=10, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Sobrenome'),
        ),
    ]
