# Generated by Django 6.0.4 on 2026-05-03 19:01

import django.utils.timezone
import encrypted_fields.fields
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', encrypted_fields.fields.EncryptedCharField(max_length=100, verbose_name='First name')),
                ('last_name', encrypted_fields.fields.EncryptedCharField(max_length=100, verbose_name='Last name')),
                ('birth_date', encrypted_fields.fields.EncryptedDateField(verbose_name='Birth date')),
                ('biological_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Biological sex')),
                ('notes', encrypted_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('q1', models.PositiveSmallIntegerField(choices=[(1, '9-11 hours'), (2, '8-9 hours'), (3, '7-8 hours'), (4, '5-7 hours'), (5, 'Less than 5 hours')], verbose_name='Q1')),
                ('q2', models.PositiveSmallIntegerField(choices=[(1, 'Less than 15 min'), (2, '15-30 min'), (3, '30-45 min'), (4, '45-60 min'), (5, 'More than 60 min')], verbose_name='Q2')),
                ('q3', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q3')),
                ('q4', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q4')),
                ('q5', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q5')),
                ('q6', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q6')),
                ('q7', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q7')),
                ('q8', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q8')),
                ('q9', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q9')),
                ('q10', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q10')),
                ('q11', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q11')),
                ('q12', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q12')),
                ('q13', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q13')),
                ('q14', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q14')),
                ('q15', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q15')),
                ('q16', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q16')),
                ('q17', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q17')),
                ('q18', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q18')),
                ('q19', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q19')),
                ('q20', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q20')),
                ('q21', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q21')),
                ('q22', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q22')),
                ('q23', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q23')),
                ('q24', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q24')),
                ('q25', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q25')),
                ('q26', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Almost always'), (5, 'Always')], verbose_name='Q26')),
            ],
            options={
                'verbose_name': 'Questionnaire response',
                'verbose_name_plural': 'Questionnaire responses',
                'ordering': ['-created'],
            },
        ),
    ]
