# Generated by Django 6.0.4 on 2026-05-03 16:15

import django.utils.timezone
import encrypted_fields.fields
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', encrypted_fields.fields.EncryptedCharField(max_length=100, verbose_name='First name')),
                ('last_name', encrypted_fields.fields.EncryptedCharField(max_length=100, verbose_name='Last name')),
                ('birth_date', encrypted_fields.fields.EncryptedDateField(verbose_name='Birth date')),
                ('biological_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Biological sex')),
                ('notes', encrypted_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created'],
            },
        ),
    ]
