# Generated by Django 6.0.4 on 2026-05-03 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='users.parent', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='patient',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_patients', to='users.specialist', verbose_name='Specialist'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_responses', to='patients.patient', verbose_name='Patient'),
        ),
    ]
