# Generated by Django 6.0.5 on 2026-05-06 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_responses', to='patients.patient', verbose_name='Patient'),
        ),
    ]
