# Generated by Django 6.0.5 on 2026-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_questionnaireresponse_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='biological_sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, null=True, verbose_name='Biological sex'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='biological_sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, verbose_name='Biological sex'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q1',
            field=models.PositiveSmallIntegerField(choices=[(1, '9-11 horas'), (2, '8-9 horas'), (3, '7-8 horas'), (4, '5-7 horas'), (5, 'Menos de 5 horas')], verbose_name='Q1'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q10',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q10'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q11',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q11'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q12',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q12'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q13',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q13'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q14',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q14'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q15',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q15'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q16',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q16'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q17',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q17'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q18',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q18'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q19',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q19'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q2',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Menos de 15 min'), (2, '15-30 min'), (3, '30-45 min'), (4, '45-60 min'), (5, 'Mais de 60 min')], verbose_name='Q2'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q20',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q20'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q21',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q21'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q22',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q22'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q23',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q23'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q24',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q24'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q25',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q25'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q26',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q26'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q3',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q3'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q4',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q4'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q5',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q5'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q6',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q6'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q7',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q7'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q8',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q8'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q9',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca'), (2, 'Ocasionalmente'), (3, 'Às vezes'), (4, 'Quase sempre'), (5, 'Sempre')], verbose_name='Q9'),
        ),
    ]
