# Generated by Django 6.0.5 on 2026-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_questionnaireresponse_biological_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
    ]
