# Generated by Django 6.0.5 on 2026-05-06 22:17

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_questionnaireresponse_professional'),
        ('users', '0003_alter_adminprofile_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_responses', to='users.parent', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=encrypted_fields.fields.EncryptedDateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_responses', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_responses', to=settings.AUTH_USER_MODEL, verbose_name='Professional'),
        ),
    ]
